apiVersion: v1
kind: ServiceAccount
metadata:
  name: self-serve-deployment-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: self-serve-deployment-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["mongodbcommunity.mongodb.com"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: self-serve-deployment-rolebinding
subjects:
  - kind: ServiceAccount
    name: self-serve-deployment-service-account
roleRef:
  kind: Role
  name: self-serve-deployment-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-serve-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-serve
  template:
    metadata:
      labels:
        app: self-serve
    spec:
      serviceAccountName: self-serve-deployment-service-account
      containers:
        - name: self-serve-api
          image: sebastianrichter/mdb-self-serve-poc-api
          ports:
            - containerPort: 8080
              hostPort: 8080
        - name: self-serve-ui
          image: sebastianrichter/mdb-self-serve-poc-ui
          ports:
            - containerPort: 80
              hostPort: 80
        - name: self-serve-db
          image: mongo
          ports:
            - containerPort: 27017
              hostPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: self-serve-srv
spec:
  type: LoadBalancer
  selector:
    app: self-serve
  ports:
    - port: 80
      name: ui
    - port: 8080
      name: api
    - port: 27017
      name: db